[[install]]
= Install

IMPORTANT: *_Canard_* uses the new gradle native dependency model.
            Thus, we highly recommend to use Gradle 6 or higher.

[[install-kmp]]
== Kotlin/Multiplatform

NOTE: Canard supports the following targets: +
jvm, iosArm32, iosArm64, iosX64, JS, tvosarm64, tvosx64, watchosarm32, watchosarm64, watchosx86, linuxArm32Hfp, linuxMips32, linuxMipsel32, linuxX64, macosX64, mingwX64.

In your `build.gradle.kts` file, add the Maven Central repository:

[source,kotlin]
----
repositories {
    mavenCentral()
}
----

Then add the dependency:

[source,kotlin,subs="attributes"]
----
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation("org.kodein.log:canard:{version}")
            }
        }
    }
}
----

[TIP]
====
If you are *NOT* using *Gradle 6+*, you should declare the use of the Gradle Metadata experimental feature

[subs="attributes"]
.settings.gradle.kts
----
enableFeaturePreview("GRADLE_METADATA")
----
====

[[install-jvm]]
== JVM & Android

On the JVM, *_Canard_* is compatible with both standard JVM and Android environments, with the same configuration.

First, add the Maven Central repository:

[source,kotlin]
----
repositories {
    mavenCentral()
}
----

Then add the dependency:

[source,kotlin,subs="attributes"]
----
dependencies {
    implementation("org.kodein.log:canard-jvm:{version}")
}
----

[[install-js]]
== JavaScript

Add the Maven Central repository:

[source,kotlin]
----
repositories {
    mavenCentral()
}
----

Then add the dependency:

[source,kotlin,subs="attributes"]
----
dependencies {
    implementation("org.kodein.log:canard-js:{version}")
}
----